services:
  flask-app:
    image: registry.cn-hangzhou.aliyuncs.com/stanley-public/ai-codereview-gitlab:1.1.0
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./.env:/app/.env
      - ./log:/app/log
      - ./data:/app/data
    restart: unless-stopped
