services:
  flask-app:
    image: crpi-cbezupzhiv8xfeaf.cn-guangzhou.personal.cr.aliyuncs.com/ppandocker/ai-codereview-gitlab:1.0.5.2
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./.env:/app/.env
      - ./log:/app/log
    restart: unless-stopped
    platform: linux/amd64