services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: ghcr.io/sunmh207/ai-codereview-gitlab:latest
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./biz:/app/biz
      - ./conf:/app/conf
      - ./conf/supervisord.dev.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./data:/app/data
      - ./log:/app/log
      - ./api.py:/app/api.py
      - ./requirements.txt:/app/requirements.txt
      - ./ui.py:/app/ui.py
    env_file:
      - ./conf/.env
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    # image: sunmh207/ai-codereview-gitlab:1.2.3-worker
    volumes_from:
      - app
    env_file:
      - ./conf/.env
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:alpine
#    ports:
#      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: